import 'package:flutter/material.dart';
import 'package:flutter_image_pick_crop/modals/Product.dart';

// class FeaturedProduct {
//   final String name;
//   final double price;
//   final String image;
//   final String description, p1, p2, p3;
//   final double p1Percent, p2Percent, p3Percent;

//   final Color bgColor;
//   final int id;

//   FeaturedProduct(
//     this.id,
//     this.name,
//     this.price,
//     this.image,
//     this.description,
//     this.p1,
//     this.p1Percent,
//     this.p2,
//     this.p2Percent,
//     this.p3,
//     this.p3Percent,
//     this.bgColor,
//   );
// }

List<Product> featuredProduct = [
  Product(
      1,
      120,
      'Gauva',
      'assests/images/[removal 8.png',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Fat',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      false,
      'Pazlam',
      30),
  Product(
      2,
      90,
      'Mango',
      'assests/images/[removal 8.png',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Nutrients',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      false,
      'Pazlam',
      30),
  Product(
      3,
      20,
      'Apple',
      'assests/images/[removal 8.png',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Fat',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      false,
      'Pazlam',
      30),
  Product(
      4,
      200,
      'Papaya',
      'assests/images/[removal 8.png',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Fat',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      true,
      'Pazlam',
      30),
  Product(
      5,
      80,
      'Orange',
      'assests/images/[removal 8.png',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Fat',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      true,
      'Pazlam',
      30),
];
