import 'package:flutter_image_pick_crop/modals/Product.dart';
import 'package:flutter/material.dart';

List<Product> vegetables = [
  Product(
      1,
      35,
      'Capsicum',
      'assests/images/Ellipse 7.png',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Nutrients',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      true,
      'Pazlam',
      30),
  Product(
      2,
      65,
      'Capsicum',
      'assests/images/Ellipse 7.png',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Nutrients',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      false,
      'Pazlam',
      30),
  Product(
      3,
      35,
      'Capsicum',
      'assests/images/Ellipse 7.png',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Nutrients',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      false,
      'Pazlam',
      30),
];
