import 'package:flutter/material.dart';
import 'package:flutter_image_pick_crop/modals/Product.dart';

// class SearchResult {
//   final String image, name, tamilName, description, p1, p2, p3;
//   final double price, offerPercent, p1Percent, p2Percent, p3Percent;
//   final Color bgColor;
//   final int id;
//   final bool isFavourite;

//   SearchResult(
//     this.image,
//     this.name,
//     this.tamilName,
//     this.price,
//     this.offerPercent,
//     this.id,
//     this.description,
//     this.p1,
//     this.p2,
//     this.p3,
//     this.p1Percent,
//     this.p2Percent,
//     this.p3Percent,
//     this.bgColor,
//     this.isFavourite,
//   );
// }

List<Product> searchResult = [
  Product(
      1,
      35,
      'Capsicum',
      'assests/images/Rectangle 256.jpg',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Nutrients',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      true,
      'Kumili',
      35),
  Product(
      1,
      35,
      'Capsicum',
      'assests/images/Rectangle 256.jpg',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Nutrients',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      false,
      'Kumili',
      35),
  Product(
      1,
      35,
      'Capsicum',
      'assests/images/Rectangle 256.jpg',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Nutrients',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      false,
      'Kumili',
      35),
  Product(
      1,
      35,
      'Capsicum',
      'assests/images/Rectangle 256.jpg',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Nutrients',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      false,
      'Kumili',
      35),
  Product(
      1,
      35,
      'Capsicum',
      'assests/images/Rectangle 256.jpg',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Nutrients',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      true,
      'Kumili',
      35),
  Product(
      1,
      35,
      'Capsicum',
      'assests/images/Rectangle 256.jpg',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Nutrients',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      false,
      'Kumili',
      35),
  Product(
      1,
      35,
      'agfsdh',
      'assests/images/Rectangle 256.jpg',
      (1 / 2),
      1,
      4,
      'Lorem \n ipsum \n dolor ',
      'Nutrients',
      85,
      'Vitamin',
      50,
      'Carbohydrate',
      60,
      Colors.red,
      true,
      'Kumili',
      35),
];
